# A dataset is a logical object that represents a set of related facts, attributes, and attribute labels.
# Datasets are basic organization units of a logical data model.
# Read more about Datasets:
# https://www.gooddata.com/developers/cloud-native/doc/cloud/model-data/concepts/dataset/

type: dataset
id: product
table_name: product

title: Product
description: Product
tags:
  - Product

primary_key: product_id

fields:
  product_brand:
    type: attribute
    source_column: product_brand
    title: Product brand
    description: Product brand
    tags:
      - Product
  product_category:
    type: attribute
    source_column: product_category
    title: Product category
    description: Product category
    tags:
      - Product
  product_id:
    type: attribute
    source_column: product_id
    title: Product id
    description: Product id
    tags:
      - Product
    labels:
      product_id_image_web:
        source_column: ls__product_id__product_id_image_web
        title: Product id image web
        description: Product id image web
        tags:
          - Product
      product_name:
        source_column: ls__product_id__product_name
        title: Product name
        description: Product name
        tags:
          - Product
  product_image:
    type: attribute
    source_column: product_image
    title: Product image
    description: Product image
    tags:
      - Product
    labels:
      product_image_web:
        source_column: ls__product_image__product_image_web
        title: Product image web
        description: Product image web
        tags:
          - Product
  product_rating:
    type: attribute
    source_column: product_rating
    title: Product rating
    description: Product rating
    tags:
      - Product
  rating:
    type: fact
    source_column: rating
    title: Rating
    description: Rating
    tags:
      - Product
